name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "15 16 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'There has been no activity on this issue for an extended period of time. This issue will be closed after further 14 days of inactivity.'
        stale-pr-message: 'There has been no activity on this Pull Request for an extended period of time. This Pull Request will be closed after further 14 days of inactivity.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-label: 'leave open'
        exempt-pr-label: 'leave open'
        days-before-stale: 90
        days-before-close: 14
        operations-per-run: 7
